config/routes.rb
Photogur::Application.routes.draw do
  
root :to => 'pictures#index'

resources :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	attr_accessible :title, :artist, :url, :copyrighted #Whitelist that allows mass-assignment for the attributes title and artist
	#don't confuse with attr_acccessor

  #validation!
  validates :title, :presence => true
  validates :url, :presence => true

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
# pictures_controller.rb

class PicturesController < ApplicationController

	# before_filter :load_pictures

	def index
		@pictures = Picture.all
	end


	def show
		# id comes from the route
		@picture = Picture.find params[:id].to_i

	end

	def new
		@picture = Picture.new
		# @picture.title = "Default"
	end

	def create

		@picture = Picture.new(params[:picture])
		
		if @picture.save
			redirect_to pictures_path
		else
			#if there was an error on the form
			flash.now[:error] = "Can't be blank"
			render :new
		end


		# @picture = Picture.new
		# @picture.url = params[:url]
		# @picture.title = params[:title]
		# @picture.artist = params[:artist]
		# success = @picture.save	

		# if success
		# 	redirect_to '/pictures' # pictures_path <= this is complicated, we'll get into it later
		# end

		# render :text => "Saving a picture. URL: #{params[:url]} Artist: #{params[:artist]} Title: #{params[:title]}" 
	
	end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
		@picture = Picture.find(params[:id])
		if @picture.update_attributes(params[:picture])	
			redirect_to @picture
		else
			render :edit
		end
	end

	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_path
	end




	# def load_pictures


		# @pictures = [
		# 	{
		# 		:title => "Megan Fox",
		# 		:artist => "Samir",
		# 		:url => 'http://serpentorslair.com/wp-content/uploads/2013/02/megan-fox-wallpaper-16.jpg'},
		# 	{
		# 		:title => "Quit Bitchin",
		# 		:artist => "Unknown",
		# 		:url => 'http://gallery.rennlist.com/albums/album441/bitch.gif'},
		# 	{
		# 		:title => "Jenga",
		# 		:artist => "Unknown",
		# 		:url => 'http://i.imgur.com/Hebp5.jpg'}
		# ]	
	# end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def copyright_text(picture)
    if picture.copyrighted?
      return "Copyrighted"
    else
      return "Not Copyrighted"
    end
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav> 

<ul>
  <li><%= link_to "Home", pictures_path %> </li>
  <li><%= link_to "New Picture", new_picture_path %></li>
</ul>

</nav>

<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<!-- edit.html.erb -->

<h1>Edit a Picture</h1>

<%= form_for @picture do |f| %>

<p>
	<label>Artist</label><br>
  <%= f.text_field "artist"%>
</p>

<p>
  <label>Title</label><br>
  <%= f.text_field "title" %>
  <p><%= @picture.errors.messages[:title].join(" ") %></p>
</p>

<p>
  <label>URL</label><br>
  <%= f.text_field "url" %>
  <p><%= @picture.errors.messages[:url].join(" ") %></p>
</p>

<p>
  <%= f.check_box "copyrighted" %>
  <%= f.label "copyrighted", "Photo is Copyrighted" %>
</p>

<p>
	<%= f.submit "Update"%>
</p>

<%end%>

app/views/pictures/index.html.erb
<h1>Pictures</h1>

<!-- <a href="/pictures/new">New Picture</a> -->
<!-- <a href="<%= new_picture_path %>" class="NewPic">New Picture</a> -->
<!-- <div class="NewPic"><%= link_to "New Pictures", new_picture_path %></div> -->

<br>

<%- @pictures.each do |picture| %>
  <div class = "box">
  <a href="<%= picture_path(picture) %>">
	<p><strong> <%= picture.title %></strong> </p>
	<p><img src="<%= picture.url %>"></p>
	<p><em>Artist: <%= picture.artist %></em></p>
  <p><a href="<%= edit_picture_path(picture)%>">Edit</a>
	</a>
  <br>
  <a> <%= link_to "Delete", picture_path(picture), :method => :delete, :confirm => "Are you sure you want to delete this picture?" %> </a>
  <br> <%=copyright_text(picture)%>

<!--
  <%= link_to picture_path(picture) do %>
    <img src="<%= picture.url%>">
  <% end %>
-->
  
  </div>
<% end %>

app/views/pictures/new.html.erb
<!-- new.html.erb -->
<h1> Add a picture! </h1>

<!-- <div class ="errors">
  <%= flash[:error] %>
</div> -->

<!-- FIRST VERSION HTML: <form action="/pictures" method="POST"> --><!--  sending something to the url therefore using POST -->

<%= form_for @picture do |f| %>

<p>
	<label>Artist</label><br>
  <%= f.text_field "artist"%>
</p>

<p>
	<label>Title</label><br>
  <%= f.text_field "title" %>
  <p><%= @picture.errors.messages[:title].join(" ") %></p>
</p>

<p>
	<label>URL</label><br>
  <%= f.text_field "url" %>
  <p><%= @picture.errors.messages[:url].join(" ") %></p>
</p>

<p>
  <%= f.check_box "copyrighted" %>
  <%= f.label "copyrighted", "Photo is Copyrighted" %>
</p>

<p>
  <%= f.submit "Save"%>
</p>

<%end%>

app/views/pictures/show.html.erb
<!--<%= params %>-->
<!-- <hr> -->

<style type="text/css">

img{
  height:40%;
  width:50%;
  vertical-align:middle;
  border: 1px solid black;
  margin-left: 25%;
}
</style>



<br>
<h1><%= @picture[:title] %></h1>
<img src="<%=@picture[:url] %>">
<p>
<a href="<%= edit_picture_path(@picture)%>"> Edit </a>
<br>
<a> <%= link_to "Delete", picture_path(@picture), :method => :delete, :confirm => "Are you sure you want to delete this picture?" %> </a>
<br><%=copyright_text(@picture)%>